version: '3.8'

services:
  parchis_db:
    image: mysql:8
    container_name: parchis_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parchis
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  parchis_backend:
    build: ./backend
    container_name: parchis_backend
    environment:
      DB_HOST: parchis_db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: parchis
      DEBUG: "socket*"
    ports:
      - "3001:3001"
    depends_on:
      parchis_db:
        condition: service_healthy
        
  parchis_frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_HOST: "http://localhost:3030/backend"    
        VITE_BACKEND_HOST_WS: "/"          
        VITE_BACKEND_HOST_WS_PATH: "/backend"            
    container_name: parchis_frontend
    ports:
      - "3000:3000"
    depends_on:
      - parchis_backend
      
  parchis_nginx:
    image: nginx:stable-alpine
    container_name: parchis_nginx
    ports:
      - "3030:80" # exponemos puerto 3000 en host a puerto 80 en nginx
    depends_on:
      - parchis_frontend
      - parchis_backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped      

volumes:
  mysql_data:

